### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by zhangpy** [natefinch/lumberjack#2]
I like the idea. 
I tested it and met an issue.
Here is the code to reproduce.

``` go
package main

import (
    "log"
    "net/http"
    "time"

    "github.com/natefinch/lumberjack"
)

func main() {
    log.SetOutput(&lumberjack.Logger{
        Dir:        "log",
        NameFormat: "2006-01-02T01-01-01.000.log",
        MaxSize:    lumberjack.Megabyte,
        MaxBackups: 3,
        MaxAge:     28,
    })

    for {
        log.Println("----")
        time.Sleep(time.Microsecond)
    }
}
```

The output is:

``` log
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x6d14c0, 0x8ba0af)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/natefinch/lumberjack.(*Logger).cleanup(0xc208004300, 0x0, 0x0)
    .../github.com/natefinch/lumberjack/lumberjack.go:269 +0x500
github.com/natefinch/lumberjack.(*Logger).rotate(0xc208004300, 0x0, 0x0)
    .../github.com/natefinch/lumberjack/lumberjack.go:179 +0xaf
github.com/natefinch/lumberjack.(*Logger).Write(0xc208004300, 0xc20803faa0, 0x19, 0x20, 0x0, 0x0, 0x0)
```

The reason is oldLogFiles() return empty slice.

**Comment by peterwillcn** [comment]
NameFormat is missing in v2 version,That's why some people continue to use the v1 version！

**Comment by peterwillcn** [comment]
> For what it's worth, I am working on v2 of lumberjack which will avoid this problem (by not letting you specify the timestamp format), so it might be worth just waiting for that.... should be out Real Soon Now.
```
func getLogWriter(outputPath string, maxLogsSizeMb int64) zapcore.WriteSyncer {
	lumberJackLogger := &lumberjack.Logger{
		Dir:        outputPath,
		NameFormat: "2006-01-02_15.04.05.log",
		MaxSize:    maxLogsSizeMb * lumberjack.Megabyte,
	}
	return zapcore.AddSync(lumberJackLogger)
}
```
Maybe it can be better designed and implemented( Such as scanning folder file count or folder volume capacity rolling), Customized file format is required.
